auto: true
server: true
permalink: /:title/
baseurl: "/blog"
paginate: 3
future: false
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata: 
    "_posts": |
      title: ""
      abstract: ""
      image: ""
      published: false
      author: Jervis Whitley
      author_twitter: procedureus
      comments: true
      layout: post
      categories:
      - automating
