auto: true
server: true
permalink: /:title/
baseurl: "/blog"
paginate: 3
future: false
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata: 
    "_posts": |
      title: Your Post Title
      abstract: Short summary of your article.
      image: http://www.example.com/link-to-image.png
      published: false
      categories:
      - automating
      author: Jervis Whitley
      author_twitter: procedureus
      comments:true
      layout: post
