auto: true
server: true
permalink: /:year/:month/:title/
baseurl: "/blog"
future: false
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata: 
    _posts/: |
      published: false
      layout: post
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: johndoe
      author: John Doe
      categories:
      - articles