auto: true
server: true
permalink: /:title/
baseurl: "/blog"
paginate: 3
future: false
exclude:
- .gitignore
- README.md
authors:
      jervis: 
        name: Jervis Whitley
        twitter: jervisw
        image: "http://www.gravatar.com/avatar/b91d2723388aa767754504a96d95a722.png"

prose:
  rooturl: "_posts"
  metadata: 
    "_posts": |
      title: ""
      abstract: ""
      image: "http://www.example.com/images/image.jpg"
      published: false
      author: jervis
      comments: true
      layout: post
      categories:
      - automating
